### ISSUE TITLE
version v3.3.1 error  unsupported file format linked (arm64)

### ISSUE THREAD

**Issue by iHTCboy** [naver/cafe-sdk-ios#17]
error:

```
ld: warning: ignoring file /Users/efun/Downloads/cafe-sdk-ios-master 2/sample/external-lib/KaleidoCore.framework/KaleidoCore, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/efun/Downloads/cafe-sdk-ios-master 2/sample/external-lib/KaleidoCore.framework/KaleidoCore
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_KFAuthentication", referenced from:
      objc-class-ref in NaverCafeSDKLive(GLKaleidoManager.o)
  "_OBJC_CLASS_$_KFConfig", referenced from:
      objc-class-ref in NaverCafeSDKLive(GLKaleidoManager.o)
  "_OBJC_CLASS_$_KFIntCounter", referenced from:
      objc-class-ref in NaverCafeSDKLive(GLLiveStreamerChatManager.o)
      objc-class-ref in NaverCafeSDKLive(GLLiveViewerChatManager.o)
      objc-class-ref in NaverCafeSDKLive(GLKaleidoManager.o)
  "_OBJC_CLASS_$_KFValue", referenced from:
      objc-class-ref in NaverCafeSDKLive(GLLiveStreamerChatManager.o)
      objc-class-ref in NaverCafeSDKLive(GLLiveViewerChatManager.o)
      objc-class-ref in NaverCafeSDKLive(GLNotificationManager.o)
  "_OBJC_CLASS_$_KFDatatypeOptions", referenced from:
      objc-class-ref in NaverCafeSDKLive(GLLiveStreamerChatManager.o)
      objc-class-ref in NaverCafeSDKLive(GLLiveViewerChatManager.o)
      objc-class-ref in NaverCafeSDKLive(GLNotificationManager.o)
  "_OBJC_CLASS_$_KFClientManager", referenced from:
      objc-class-ref in NaverCafeSDKLive(GLKaleidoManager.o)
  "_OBJC_CLASS_$_KFVariable", referenced from:
      objc-class-ref in NaverCafeSDKLive(GLLiveStreamerChatManager.o)
      objc-class-ref in NaverCafeSDKLive(GLLiveViewerChatManager.o)
      objc-class-ref in NaverCafeSDKLive(GLNotificationManager.o)
      objc-class-ref in NaverCafeSDKLive(GLKaleidoManager.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

the Demo same too error!

**Comment by iHTCboy** [comment]
Can someone give me a hand？

**Comment by iHTCboy** [comment]
Hi, tech brother. When will we have a fix？:-

**Comment by gguogguo** [comment]
I have exactly same issue.

**Comment by iHTCboy** [comment]
@gguogguo  remove KaleidoCore.framework and NaverCafeSDKLive.framework with version 3.3.1 ，it run gook job！but  v 4.0.x Depend on each other~

**Comment by AlanCBaek** [comment]
Fixed at the version 4.4.7.
